import { useMigrations } from "drizzle-orm/expo-sqlite/migrator";
import { Stack } from "expo-router";
import * as SplashScreen from "expo-splash-screen";
import { useEffect } from "react";
import { db } from "../db";
import "../i18n"; // Initializes the translation engine

// This file will be generated by Drizzle in the next step.
// Don't worry if your editor shows a red squiggly line here right now!
import migrations from "../db/migrations/migrations";

// Prevent the splash screen from auto-hiding before DB migrations finish.
SplashScreen.preventAutoHideAsync();

export default function RootLayout() {
  // This hook runs our SQLite migrations on the user's device when the app boots
  const { success, error } = useMigrations(db, migrations);

  useEffect(() => {
    if (success) {
      // Migrations are done, database is ready. Hide the splash screen.
      SplashScreen.hideAsync();
    }
    if (error) {
      console.error("Database migration error:", error);
      // In a real app, you might want to show a fallback UI here,
      // but logging is fine for our current development stage.
    }
  }, [success, error]);

  // Keep the UI rendering null (showing the native splash screen) until SQLite is ready
  if (!success) {
    return null;
  }

  return (
    <Stack screenOptions={{ headerShown: false }}>
      <Stack.Screen name="(tabs)" />
      <Stack.Screen name="add-alert" options={{ presentation: "modal" }} />
    </Stack>
  );
}
